In [22]:
import numpy as np
import pandas as pd

In [23]:
ls1 = [1,2,3]
ls2 = [4,5,6]
rs = []
rs.extend(ls1)
rs.extend(ls2)
rs

[1, 2, 3, 4, 5, 6]

In [24]:
rs = ls1 + ls2
rs

[1, 2, 3, 4, 5, 6]

In [26]:
ls1[slice(0,2)], ls1[0:2], ls1[:2]

([1, 2], [1, 2], [1, 2])

In [27]:
list(reversed(ls1)), ls1[::-1]

([3, 2, 1], [3, 2, 1])

[3, 2, 1]

In [18]:
for i,v in enumerate(set(zip(ls1, ls2))):
    print(v)

set(zip(ls1, ls2))

(2, 5)
(1, 4)
(3, 6)


{(1, 4), (2, 5), (3, 6)}

In [18]:
numbers = [1,2,3,4,5]
numbers +=[6,7,8,9,10]
list(map(lambda x: x**2, numbers))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [21]:
list(filter(lambda x: x % 2 == 0, numbers))

[2, 4, 6, 8, 10]

In [4]:
def add(x,y):
    return x+y
callable(add)

True

In [30]:
first, *_ = (1,2,3)
first

1

In [38]:
pet = {"age": 5, "name": "Fido", "species": "dog"}
# del pet["age"]
pet.pop("age")
# pet

5

In [40]:
matrix = [[i*j for j in range(3)] for i in range(3)]
matrix

[[0, 0, 0], [0, 1, 2], [0, 2, 4]]

In [46]:
{word: len(word) for word in ["hello", "world"]}
sum([len(word) for word in ["hello", "world"]])

10

In [62]:
set(dict.fromkeys(["a", "c", "b"], 1).keys())

{'a', 'b', 'c'}

In [60]:
list({"a": 1, "b": 2, "c": 3}.values())

[1, 2, 3]

In [64]:
from collections import Counter
Counter(["a", "b", "c", "a", "b", "a"])

Counter({'a': 3, 'b': 2, 'c': 1})

In [70]:
# sorted(["a", "b", "c", "a", "b", "a"], reverse=True)
reversed(sorted(["a", "b", "c", "a", "b", "a"]))

In [77]:
ls = ["a", "b", "c", "a", "b", "1"]
ls[::-1]

['1', 'b', 'a', 'c', 'b', 'a']

In [79]:
5/float(2)

2.5

In [81]:
[1,2,3]*2 #+ [4,5,6]

[1, 2, 3, 1, 2, 3]

In [82]:
np.array([1,2,3]) * 2 #+ np.array([4,5,6])

array([2, 4, 6])

In [83]:
"abc"*2

'abcabc'

In [91]:
np.log1p([1,2,3])

array([0.69314718, 1.09861229, 1.38629436])

In [122]:
np.ones((3,4)), list(np.arange(3)), np.full((3,4), 7), np.eye(3), np.empty((3,4)),# np.random.rand(3,4)

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 [np.int64(0), np.int64(1), np.int64(2)],
 array([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[0.51391815, 0.52180876, 0.01838344, 0.37818705],
        [0.4569655 , 0.91116002, 0.62943222, 0.63601442],
        [0.71210932, 0.34138871, 0.95061322, 0.16629299]]))

In [135]:
np.random.rand(3,4).size, np.float64

(12, numpy.float64)

In [155]:
np.ravel((np.eye(3) + np.eye(3)))

array([2., 0., 0., 0., 2., 0., 0., 0., 2.])

In [156]:
(np.eye(3) + np.eye(3)).T.reshape(1,9)

array([[2., 0., 0., 0., 2., 0., 0., 0., 2.]])

In [162]:
np.vstack((np.eye(3), np.eye(3)))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [166]:
np.array([[1, 2, 3], [4, 5, 6]]), np.array([(1, 2, 3), (4, 5, 6)])

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))